---
author: "Francisco José Lozano Ruiz"
date: "27/10/2017"
documentclass: book
forprint: true  # true: imprime a dos caras, false: libro digital
fontsize: 12pt # 10pt,11pt
geometry: margin = 2.5cm 
bibliography: ["bib/library.bib", "bib/paquetes.bib"]
# metodobib -> true: natbib (descomentar: citation_package: natbib) 
#           -> false: pandoc (comentar: citation_package: natbib)
metodobib: true
#natbib: plainnat, abbrvnat, unsrtnat
biblio-style: "plainnat"
#Método 2 (pandoc): descomente una línea de las 2 siguientes en caso de usarlo
csl: methods-in-ecology-and-evolution.csl      # no numera mejor en las citas
#csl: acm-sig-proceedings-long-author-list.csl  # numera peor en las citas
link-citations: yes
output: 
  pdf_document:
    keep_tex: no
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    #toc: yes
    fig_caption: yes
    template: latex/templateMemoriaTFE.tex
    includes:
      #before_body: portadas/latex_paginatitulo_modTFE.tex
      #in_header: latex/latex_preambulo.tex
      #after_body: latex/latex_antes_enddoc.tex
---


```{r include=FALSE}
#Sys.setlocale('LC_ALL','C') # corrige problema con 
options(kableExtra.latex.load_packages = F)
#options(tinytex.latexmk.emulation = FALSE)
knitr::opts_chunk$set(fig.path = 'figurasR/',
                      echo = FALSE, warning = FALSE, message = FALSE,
                      fig.pos="H",fig.align="center",out.width="95%",
                      cache=FALSE)
knitr::write_bib(c("knitr","rmarkdown","dplyr","ggplot2","kableExtra"),
                 file="bib/paquetes.bib", width = 60)
```


<!-- \setcounter{chapter}{2} -->
<!-- \setcounter{chapter}{2} escribir 2 para capítulo 3  -->
<!-- \pagenumbering{arabic} -->


\ifdefined\ifprincipal
\else
\setlength{\parindent}{1em}
\pagestyle{fancy}
\setcounter{tocdepth}{4}
\tableofcontents
<!-- \subpdfbookmark{Índice General}{indice} -->
\nocite{Luque2017,Luque2019,RStudio,R-base,
R-knitr,R-rmarkdown,R-dplyr,R-ggplot2,Techopedia}

\fi

\ifdefined\ifdoblecara
\fancyhead{}{}
\fancyhead[LE,RO]{\scriptsize\rightmark}
\fancyfoot[LO,RE]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[LE,RO]{\footnotesize\thepage}
\else
\fancyhead{}{}
\fancyhead[RO]{\scriptsize\rightmark}
\fancyfoot[LO]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[RO]{\footnotesize\thepage}
\fi

\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

# Conclusión

 Por un lado, durante el proyecto se ha podido observar que los modelos aditivos generalizados mejoran la metodología de los MLG incorporando la flexibilidad que aporta la regresión no paramétrica y además mantienen la interpretabilidad de los datos del análisis de regresión con múltiples variables predictoras. Actualmente, estos modelos son un punto de partida magnífico para el modelado de un problema, un MAG bien ajustado debería funcionar de manera conveniente, incluso comparado con métodos de *boosting* o de *deep learning*. Además, el MAG tiene una base para una mejor interpretabilidad y métricas de incertidumbre más sencillas, por lo que en muchos problemas asociados al análisis de datos, los Modelos Aditivos Generalizados son una buena opción.
 
 Por otro lado, también se han presentado resultados objetivos de la existencia del cambio climático y de la gravedad de sus consecuencias, tanto en el capítulo 4 con el apoyo de artículos e invetigaciones realizadas por organizaciones, como en el capítulo 5 con tres aplicaciones de los modelos aditivos generalizados. La primera y la tercera nos sirven para comprobar algunos de los impactos que el cambio climático está teniendo sobre el planeta y la segunda nos permite analizar la tendencia de los gases de efecto invernadero en las últimas décadas. Con los datos que se manejan no es posible asegurar el efecto que la humanidad sobre este tema, sin embargo, nos podemos referir a los informes del IPCC (@OficinaCC) para obtener resultados objetivos que aseguran las implicaciones que tiene la actividad humana en él. Además, en estos informes podemos encontrar estudios de los posibles escenarios y estrategias para la mitigación o la adaptación a ellos. 
 
 En conclusión, el uso de modelos aditivos generalizados no solo ayuda a la comprensión del cambio climático, sino que también proporciona una base sólida para la toma de decisiones y la planificación a largo plazo de métodos para su desaceleración. La flexibilidad y precisión que ofrecen los MAG los convierten en una herramienta invaluable para abordar los desafíos impuestos por uno de los problemas más urgentes de nuestro tiempo, el cambio climático.
 
 